In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [6]:
#loading data
df = pd.read_csv('data/training.csv', encoding='latin-1')
df.head()

                                                text  label
0                            i didnt feel humiliated      0
1  i can go from feeling so hopeless to so damned...      0
2   im grabbing a minute to post i feel greedy wrong      3
3  i am ever feeling nostalgic about the fireplac...      2
4                               i am feeling grouchy      3

In [7]:
df.isnull().sum()

text     0
label    0
dtype: int64

In [8]:
df['text'] = df['text'].apply(lambda x: x.lower())
df.head()

                                                text  label
0                            i didnt feel humiliated      0
1  i can go from feeling so hopeless to so damned...      0
2   im grabbing a minute to post i feel greedy wrong      3
3  i am ever feeling nostalgic about the fireplac...      2
4                               i am feeling grouchy      3

In [20]:
import string
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))
df['text'] = df['text'].apply(remove_punctuation)
df.head()

                                                text  label
0                              didnt feel humiliated      0
1  go feeling hopeless damned hopeful around some...      0
2          im grabbing minute post feel greedy wrong      3
3  ever feeling nostalgic fireplace know still pr...      2
4                                    feeling grouchy      3

In [21]:
def reove_numbers(text):
    return text.translate(str.maketrans('', '', string.digits))
df['text'] = df['text'].apply(reove_numbers)

In [22]:
#removing emojis
def remove_emojis(text):
    new = ""
    for i in text:
        if i.isascii():
            new += i
    return new
df['text'] = df['text'].apply(remove_emojis)

In [23]:
#remove stop words
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /Users/richa/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [24]:
stop_words = set(stopwords.words('english'))
def remove_stop_words(text):
    return ' '.join([word for word in text.split() if word not in stop_words])
df['text'] = df['text'].apply(remove_stop_words)

In [ ]:
# #boW
# from sklearn.feature_extraction.text import CountVectorizer
# vectorizer = CountVectorizer()
# X = vectorizer.fit_transform(df['text'])
# y = df['label']
# print("vocabulary:", vectorizer.vocabulary_)

vocabulary: {'didnt': 3586, 'feel': 4887, 'humiliated': 6372, 'go': 5634, 'feeling': 4891, 'hopeless': 6284, 'damned': 3176, 'hopeful': 6282, 'around': 690, 'someone': 12275, 'cares': 1927, 'awake': 916, 'im': 6495, 'grabbing': 5690, 'minute': 8373, 'post': 10050, 'greedy': 5751, 'wrong': 14901, 'ever': 4526, 'nostalgic': 8971, 'fireplace': 5016, 'know': 7352, 'still': 12622, 'property': 10329, 'grouchy': 5789, 'ive': 6986, 'little': 7728, 'burdened': 1749, 'lately': 7456, 'wasnt': 14521, 'sure': 12954, 'taking': 13111, 'milligrams': 8332, 'times': 13472, 'recommended': 10724, 'amount': 456, 'fallen': 4778, 'asleep': 755, 'lot': 7829, 'faster': 4824, 'also': 408, 'like': 7658, 'funny': 5403, 'confused': 2650, 'life': 7633, 'teenager': 13220, 'jaded': 7000, 'year': 14954, 'old': 9150, 'man': 7994, 'petronas': 9723, 'years': 14962, 'performed': 9651, 'well': 14607, 'made': 7935, 'huge': 6351, 'profit': 10287, 'romantic': 11224, 'make': 7970, 'suffering': 12861, 'seeing': 11605, 'mean': 8162, 'something': 12279, 'running': 11307, 'divine': 3807, 'experience': 4656, 'expect': 4646, 'type': 13867, 'spiritual': 12418, 'encounter': 4318, 'think': 13368, 'easiest': 4104, 'time': 13467, 'dissatisfied': 3762, 'low': 7856, 'energy': 4352, 'thirsty': 13375, 'immense': 6518, 'sympathy': 13067, 'general': 5491, 'point': 9951, 'possible': 10048, 'proto': 10358, 'writer': 14893, 'trying': 13791, 'find': 4992, 'write': 14892, 'corners': 2847, 'sign': 11929, 'agent': 286, 'let': 7595, 'alone': 399, 'publishing': 10417, 'contract': 2770, 'feels': 4894, 'precious': 10118, 'reassured': 10684, 'anxiety': 570, 'side': 11911, 'really': 10674, 'embarrassed': 4249, 'pretty': 10196, 'pathetic': 9544, 'started': 12549, 'sentimental': 11671, 'dolls': 3846, 'child': 2180, 'began': 1148, 'collection': 2439, 'vintage': 14361, 'barbie': 1035, 'sixties': 12004, 'compromised': 2583, 'skeptical': 12015, 'value': 14237, 'every': 4529, 'unit': 14042, 'work': 14833, 'put': 10472, 'irritated': 6946, 'rejected': 10827, 'without': 14782, 'anyone': 576, 'anything': 578, 'saying': 11452, 'completely': 2561, 'overwhelmed': 9365, 'two': 13859, 'strategies': 12690, 'help': 6100, 'grounded': 5791, 'pour': 10075, 'heart': 6044, 'journal': 7131, 'form': 5229, 'letter': 7601, 'god': 5638, 'end': 4325, 'list': 7709, 'five': 5035, 'things': 13366, 'grateful': 5734, 'amused': 467, 'delighted': 3378, 'able': 24, 'chai': 2064, 'lifeline': 7634, 'support': 12935, 'encouragement': 4322, 'great': 5744, 'glad': 5584, 'already': 406, 'fucked': 5369, 'though': 13387, 'dont': 3861, 'usually': 14202, 'eat': 4111, 'morning': 8536, 'love': 7845, 'wish': 14765, 'best': 1233, 'longer': 7791, 'tolerate': 13532, 'effect': 4162, 'bm': 1435, 'lives': 7737, 'fact': 4750, 'turned': 13826, 'bitter': 1320, 'angry': 508, 'person': 9686, 'always': 426, 'particularly': 9503, 'kind': 7300, 'people': 9629, 'stressed': 12706, 'inhibited': 6715, 'elses': 4231, 'kitchen': 7319, 'painting': 9423, 'picture': 9786, 'become': 1124, 'defeated': 3331, 'kinda': 7301, 'appalled': 607, 'needs': 8800, 'explain': 4666, 'wide': 14696, 'lenghth': 7573, 'body': 1452, 'measures': 8172, 'etc': 4487, 'pp': 10086, 'superior': 12916, 'dead': 3251, 'chicken': 2175, 'grieving': 5766, 'get': 5533, 'giddy': 5551, 'elegant': 4213, 'perfectly': 9647, 'fitted': 5033, 'pencil': 9617, 'skirt': 12038, 'remember': 10891, 'acutely': 154, 'distressed': 3787, 'days': 3242, 'seen': 11615, 'heard': 6040, 'read': 10646, 'past': 9533, 'couple': 2898, 'left': 7545, 'impressed': 6557, 'companies': 2528, 'climbed': 2332, 'hill': 6167, 'frustrated': 5362, 'id': 6442, 'much': 8618, 'paced': 9389, 'entirely': 4404, 'course': 2903, 'factor': 4751, 'never': 8853, 'hampered': 5900, 'dent': 3416, 'day': 3236, 'imagine': 6503, 'real': 10659, 'scenario': 11480, 'would': 14868, 'emotionally': 4278, 'connected': 2663, 'enough': 4376, 'totally': 13586, 'accepted': 67, 'safe': 11354, 'morally': 8523, 'acceptable': 64, 'close': 2350, 'prolonged': 10310, 'physical': 9764, 'contact': 2732, 'sex': 11726, 'expected': 4649, 'subsequently': 12822, 'content': 2749, 'need': 8791, 'creative': 2978, 'however': 6335, 'want': 14482, 'causing': 2004, 'less': 7588, 'splendid': 12428, 'self': 11632, 'step': 12598, 'away': 923, 'bit': 1308, 'rude': 11283, 'writing': 14897, 'elderly': 4204, 'gentleman': 5511, 'ask': 751, 'gifts': 5555, 'christmas': 2231, 'mild': 8320, 'greed': 5750, 'protected': 10348, 'small': 12120, 'season': 11577, 'words': 14831, 'plan': 9869, 'share': 11766, 'everyday': 4533, 'stories': 12662, 'traveling': 13691, 'adventures': 230, 'inspirations': 6773, 'handmade': 5916, 'creations': 2977, 'hope': 6280, 'inspired': 6775, 'trees': 13713, 'got': 5676, 'festive': 4922, 'spurring': 12482, 'book': 1491, 'worn': 14851, 'concealer': 2591, 'brave': 1592, 'pale': 9437, 'perfect': 9645, 'strongly': 12741, 'passionate': 9528, 'jerk': 7061, 'decides': 3292, 'poke': 9960, 'fun': 5390, 'us': 14185, 'discouraged': 3691, 'robbing': 11193, 'peter': 9720, 'pay': 9570, 'paul': 9560, 'cow': 2920, 'cant': 1876, 'afford': 264, 'way': 14542, 'listless': 7718, 'new': 8858, 'different': 3596, 'lost': 7828, 'special': 12369, 'mind': 8344, 'worry': 14854, 'sane': 11399, 'wanted': 14484, 'felt': 4903, 'reading': 10651, 'many': 8035, 'said': 11361, 'sam': 11383, 'guarantee': 5811, 'used': 14192, 'paragraph': 9471, 'tell': 13232, 'sad': 11344, 'first': 5022, 'home': 6237, 'mine': 8350, 'boat': 1441, 'trip': 13748, 'denmark': 3411, 'stopped': 12655, 'cold': 2423, 'hot': 6318, 'dough': 3900, 'found': 5253, 'selfish': 11633, 'spoiled': 12434, 'stymied': 12793, 'wrote': 14906, 'unsure': 14120, 'might': 8312, 'somewhere': 12285, 'story': 12667, 'unintended': 14035, 'bag': 983, 'qaf': 10485, 'look': 7798, 'cryin': 3070, 'jacynthe': 6999, 'lookin': 7800, 'good': 5658, 'feelin': 4890, 'gorgeous': 5671, 'rupaul': 11310, 'skins': 12033, 'scissor': 11513, 'sisters': 11989, 'valentine': 14228, 'sun': 12898, 'fed': 4871, 'kayle': 7241, 'daddy': 3157, 'gerling': 5524, 'unkind': 14052, 'basically': 1065, 'fake': 4775, 'realm': 10675, 'science': 11507, 'fiction': 4938, 'hate': 5988, 'living': 7739, 'dads': 3159, 'roof': 11231, 'gives': 5581, 'excuse': 4598, 'asshole': 778, 'hes': 6132, 'providing': 10372, 'live': 7730, 'unwelcome': 14135, 'ill': 6482, 'leave': 7533, 'keep': 7244, 'pleasantly': 9910, 'surprised': 12969, 'supportiveness': 12941, 'ease': 4100, 'situations': 12001, 'anymore': 575, 'vigorous': 14349, 'sexual': 11730, 'activity': 144, 'coming': 2487, 'yes': 14971, 'misspelt': 8410, 'cumming': 3095, 'parts': 9511, 'begin': 1151, 'fall': 4777, 'mom': 8471, 'graceful': 5693, 'warm': 14496, 'loving': 7855, 'smile': 12135, 'rob': 11191, 'nurture': 9033, 'heal': 6030, 'talk': 13119, 'brother': 1664, 'law': 7484, 'extremely': 4715, 'popular': 10008, 'one': 9172, 'stiff': 12621, 'ate': 805, 'could': 2875, 'gentle': 5510, 'tingle': 13480, 'throughout': 13418, 'almost': 397, 'healing': 6032, 'place': 9861, 'cellular': 2036, 'level': 7606, 'pressured': 10181, 'young': 14993, 'beautiful': 1119, 'thin': 13364, 'depending': 3430, 'trend': 13719, 'girls': 5574, 'rejuvenated': 10833, 'butt': 1786, 'implants': 6539, 'several': 11721, 'week': 14579, 'tortured': 13577, 'hallucinations': 5896, 'moving': 8601, 'figures': 4963, 'sounds': 12334, 'vibrations': 14324, 'nearly': 8781, 'finished': 5004, 'detox': 3526, 'amazing': 429, 'back': 958, 'former': 5234, 'posts': 10058, 'asked': 752, 'prayers': 10110, 'others': 9276, 'considered': 2693, 'may': 8141, 'deserve': 3467, 'answered': 547, 'pain': 9414, 'parents': 9485, 'enraged': 4379, 'becomes': 1125, 'violent': 14365, 'roller': 11217, 'coaster': 2389, 'emotions': 4281, 'supposed': 12944, 'feelings': 4893, 'unpleasant': 14077, 'suppose': 12943, 'truth': 13784, 'shared': 11767, 'havent': 6005, 'faithful': 4772, 'dwelled': 4069, 'doubt': 3893, 'uncertainty': 13922, 'faith': 4771, 'bought': 1534, 'clearly': 2313, 'makeup': 7975, 'miserable': 8386, 'proudest': 10361, 'mum': 8645, 'earth': 4096, 'figure': 4961, 'family': 4791, 'loves': 7853, 'matter': 8129, 'else': 4230, 'michelle': 8298, 'goes': 5646, 'ballistic': 1004, 'necessarily': 8784, 'bombs': 1475, 'necessary': 8785, 'see': 11601, 'print': 10227, 'journals': 7136, 'ovaries': 9316, 'aching': 116, 'talking': 13122, 'chris': 2224, 'mostly': 8551, 'took': 13557, 'pictures': 9788, 'unimportant': 14029, 'stuff': 12768, 'tired': 13494, 'ready': 10656, 'finding': 4993, 'given': 5579, 'unsuitable': 14116, 'images': 6499, 'blamed': 1342, 'result': 11047, 'sit': 11990, 'successfully': 12842, 'manage': 7995, 'stretch': 12711, 'mxm': 8691, 'canvas': 1881, 'achievement': 113, 'worthwhile': 14865, 'usage': 14187, 'money': 8490, 'use': 14191, 'future': 5413, 'briefs': 1632, 'nay': 8773, 'important': 6548, 'honored': 6270, 'influence': 6686, 'talented': 13115, 'fully': 5387, 'alive': 374, 'girl': 5570, 'woman': 14805, 'angered': 503, 'firey': 5017, 'piece': 9791, 'garbage': 5447, 'leanne': 7520, 'thought': 13388, 'miss': 8400, 'drove': 3995, 'dannika': 3197, 'school': 11501, 'rushed': 11315, 'greeted': 5755, 'corner': 2846, 'hellip': 6098, 'furious': 5405, 'shooter': 11846, 'happy': 5945, 'excited': 4589, 'since': 11962, 'learned': 7524, 'shows': 11888, 'show': 11879, 'horses': 6308, 'trusting': 13780, 'relaxed': 10850, 'quiet': 10515, 'handled': 5914, 'frequently': 5318, 'start': 12548, 'december': 3285, 'done': 3856, 'smug': 12158, 'realize': 10670, 'everything': 4537, 'ok': 9145, 'worthless': 14863, 'struggling': 12752, 'lay': 7491, 'bed': 1129, 'dark': 3202, 'terrified': 13279, 'least': 7531, 'meet': 8200, 'airport': 327, 'supportive': 12940, 'arms': 686, 'today': 13513, 'mood': 8511, 'strange': 12681, 'entire': 4402, 'guess': 5817, 'mums': 8650, 'passed': 9518, 'involved': 6913, 'car': 1900, 'accident': 75, 'bringing': 1639, 'present': 10167, 'exams': 4570, 'flying': 5152, 'colours': 2459, 'letting': 7603, 'animosity': 518, 'towards': 13613, 'wronged': 14902, 'dogs': 3840, 'cannot': 1872, 'understand': 13956, 'decided': 3290, 'throwing': 13420, 'shitty': 11831, 'shit': 11829, 'paper': 9464, 'starting': 12552, 'wryly': 14908, 'banal': 1012, 'comedy': 2476, 'errors': 4458, 'turning': 13827, 'vital': 14389, 'bodies': 1449, 'hear': 6039, 'owners': 9377, 'victimized': 14329, 'associations': 789, 'attorneys': 856, 'manager': 7999, 'say': 11451, 'goodbye': 5659, 'fam': 4785, 'theyre': 13355, 'crying': 3071, 'heartless': 6055, 'bitch': 1309, 'hey': 6140, 'spend': 12394, 'another': 543, 'country': 2895, 'wont': 14819, 'cry': 3069, 'lily': 7669, 'going': 5648, 'opportunities': 9211, 'lasted': 7452, 'short': 11855, 'months': 8509, 'alba': 345, 'fitting': 5034, 'ton': 13545, 'catching': 1984, 'word': 14830, 'helps': 6106, 'hard': 5951, 'works': 14845, 'obtain': 9083, 'high': 6153, 'technical': 13206, 'skill': 12021, 'wushu': 14913, 'ashamed': 741, 'somehow': 12272, 'motivated': 8560, 'saw': 11450, 'kids': 7287, 'performances': 9650, 'whole': 14679, 'heartedly': 6054, 'despite': 3492, 'tiredness': 13495, 'getting': 5537, 'overwhelming': 9366, 'spritz': 12477, 'toner': 13548, 'calm': 1837, 'soothe': 12307, 'effort': 4176, 'required': 10972, 'better': 1243, 'situation': 12000, 'whether': 14646, 'member': 8222, 'college': 2443, 'friend': 5330, 'neighbor': 8812, 'street': 12698, 'even': 4519, 'complete': 2559, 'stranger': 12683, 'tree': 13712, 'soon': 12298, 'goings': 5649, 'ons': 9181, 'coronation': 2850, 'seriously': 11695, 'alright': 407, 'class': 2290, 'combination': 2465, 'unsuccessful': 14115, 'stress': 12705, 'late': 7455, 'horrible': 6299, 'resulted': 11048, 'grappling': 5730, 'rarely': 10609, 'advances': 226, 'cause': 2001, 'stick': 12615, 'rule': 11297, 'posting': 10054, 'online': 9179, 'wouldnt': 14869, 'prepared': 10158, 'somebodys': 12270, 'face': 4741, 'useful': 14193, 'pains': 9419, 'becoming': 1126, 'group': 5794, 'idea': 6444, 'ugly': 13886, 'inclined': 6605, 'wear': 14556, 'ratty': 10621, 'jeans': 7048, 'sweatshirt': 13022, 'dress': 3961, 'pair': 9426, 'heels': 6080, 'house': 6327, 'boost': 1500, 'esteem': 4480, 'slightly': 12077, 'definitely': 3352, 'bother': 1523, 'buy': 1795, 'homesick': 6250, 'yet': 14974, 'dance': 3181, 'workout': 14842, 'fabulous': 4740, 'eyes': 4731, 'touch': 13592, 'assuredly': 799, 'return': 11070, 'shall': 11750, 'vain': 14226, 'friday': 5327, 'awful': 929, 'cramps': 2945, 'honoured': 6271, 'call': 1829, 'friends': 5333, 'brotherhood': 1665, 'begun': 1156, 'apprehensive': 636, 'thick': 13358, 'black': 1328, 'rain': 10567, 'clouds': 2362, 'stormed': 12664, 'sky': 12042, 'town': 13618, 'stated': 12563, 'reason': 10680, 'fearful': 4855, 'unsafe': 14099, 'shaken': 11746, 'tsa': 13793, 'quite': 10525, 'pulled': 10422, 'croissants': 3027, 'lunch': 7894, 'groups': 5795, 'awkward': 932, 'overcompensate': 9327, 'talkative': 13120, 'finally': 4985, 'companion': 2529, 'especially': 4470, 'lonely': 7786, 'disappoint': 3658, 'loved': 7848, 'blog': 1387, 'img': 6510, 'src': 12501, 'http': 6342, 'eager': 4078, 'quilting': 10521, 'horny': 6297, 'lets': 7599, 'poem': 9944, 'pressure': 10180, 'uncomfortable': 13928, 'sense': 11659, 'understanding': 13958, 'land': 7425, 'raising': 10576, 'son': 12286, 'father': 4832, 'ancestral': 483, 'shower': 11883, 'questioning': 10509, 'fantastic': 4805, 'confident': 2634, 'movement': 8594, 'effortlessly': 4177, 'energetic': 4345, 'bouncy': 1541, 'gym': 5858, 'run': 11301, 'outside': 9307, 'take': 13104, 'pram': 10101, 'long': 7788, 'walk': 14459, 'often': 9136, 'three': 13400, 'strong': 12738, 'burst': 1770, 'tears': 13198, 'devastating': 3532, 'release': 10852, 'thoughts': 13391, 'seemed': 11611, 'rich': 11123, 'space': 12345, 'dumping': 4045, 'pumpkin': 10432, 'spice': 12400, 'latte': 7463, 'last': 7451, 'thing': 13365, 'coffee': 2406, 'maybe': 8142, 'badly': 979, 'shes': 11801, 'hyperchondria': 6417, 'exaggeration': 4562, 'habit': 5863, 'openly': 9196, 'questioned': 10508, 'clench': 2316, 'assured': 798, 'called': 1831, 'figured': 4962, 'right': 11138, 'name': 8726, 'utterly': 14214, 'affirmed': 263, 'question': 10506, 'perhaps': 9657, 'office': 9125, 'nice': 8879, 'hair': 5880, 'rebellious': 10690, 'celebrates': 2025, 'eid': 4191, 'wash': 14516, 'generous': 5504, 'sleep': 12060, 'deprived': 3446, 'sleeping': 12061, 'night': 8897, 'giving': 5582, 'bloging': 1391, 'sitting': 11998, 'amp': 459, 'cat': 1979, 'lucky': 7876, 'woke': 14802, 'sick': 11906, 'dog': 3839, 'protect': 10347, 'witch': 14774, 'hunt': 6390, 'repressed': 10957, 'memory': 8230, 'therapy': 13345, 'disgusted': 3712, 'associated': 787, 'race': 10538, 'nationality': 8757, 'laughed': 7468, 'bitterly': 1321, 'wished': 14766, 'knew': 7338, 'hated': 5989, 'forever': 5216, 'mellow': 8211, 'soft': 12239, 'easy': 4109, 'beginning': 1152, 'told': 13530, 'indecisive': 6632, 'genre': 5508, 'disservice': 3764, 'resolved': 11005, 'artifically': 717, 'artistic': 723, 'manitz': 8022, 'draw': 3942, 'circle': 2258, 'dot': 3887, 'bigger': 1270, 'line': 7683, 'accent': 61, 'mark': 8056, 'spanish': 12352, 'pissed': 9843, 'brazil': 1595, 'bus': 1775, 'steep': 12590, 'mountain': 8578, 'hills': 6169, 'middle': 8304, 'big': 1268, 'storm': 12663, 'wondering': 14815, 'whimper': 14650, 'unloved': 14063, 'uncared': 13918, 'certainly': 2054, 'whats': 14632, 'personal': 9688, 'curious': 3105, 'youd': 14991, 'watch': 14526, 'sorry': 12320, 'humor': 6377, 'foot': 5190, 'door': 3872, 'world': 14847, 'walking': 14461, 'trails': 13643, 'fells': 4902, 'mountains': 8579, 'whatever': 14629, 'comes': 2477, 'directly': 3640, 'jealous': 7043, 'insecure': 6751, 'trust': 13778, 'worthy': 14866, 'sweet': 13028, 'holiday': 6221, 'influenced': 6687, 'dash': 3213, 'happiness': 5942, 'emily': 4267, 'dickinson': 3582, 'example': 4568, 'dashes': 3216, 'instead': 6784, 'colons': 2449, 'semi': 11642, 'enhance': 4363, 'enjambment': 4364, 'sonnet': 12293, 'fatter': 4837, 'remain': 10882, 'control': 2785, 'peanut': 9588, 'butter': 1787, 'bread': 1599, 'impossible': 6551, 'looking': 7801, 'third': 13374, 'hell': 6096, 'needy': 8801, 'neglected': 8808, 'claim': 2274, 'redeem': 10748, 'beating': 1115, 'head': 6014, 'wall': 14463, 'either': 4196, 'classes': 2291, 'intimidated': 6873, 'concept': 2596, 'lit': 7720, 'groggy': 5782, 'routine': 11263, 'view': 14341, 'isnt': 6959, 'thats': 13322, 'fine': 4995, 'hold': 6214, 'shocked': 11836, 'awe': 924, 'wonder': 14810, 'rumour': 11300, 'st': 12506, 'exam': 4563, 'results': 11050, 'fear': 4853, 'failures': 4764, 'valued': 14238, 'appreciated': 632, 'arent': 669, 'anywhere': 582, 'nature': 8763, 'relationship': 10843, 'changes': 2089, 'distracted': 3781, 'regularly': 10815, 'relaxing': 10851, 'music': 8674, 'invigorated': 6905, 'afterward': 280, 'tend': 13253, 'practice': 10091, 'shut': 11898, 'youtube': 15000, 'influences': 6688, 'trends': 13721, 'specifically': 12377, 'tango': 13135, 'shy': 11901, 'maks': 7978, 'opposite': 9215, 'far': 4808, 'pics': 9785, 'lol': 7778, 'weird': 14598, 'slept': 12068, 'okay': 9146, 'thinking': 13370, 'earlier': 4086, 'heres': 6120, 'cooped': 2818, 'restless': 11036, 'weight': 14591, 'fit': 5029, 'tiny': 13487, 'unable': 13900, 'presence': 10166, 'fan': 4794, 'current': 3113, 'president': 10176, 'conservative': 2686, 'enclose': 4314, 'verses': 14308, 'weigh': 14587, 'odd': 9104, 'complacent': 2552, 'vulnerable': 14432, 'parenting': 9484, 'punished': 10440, 'stupid': 12783, 'chastised': 2123, 'behaving': 1161, 'stay': 12578, 'simply': 11956, 'contented': 2750, 'cut': 3133, 'everyone': 4535, 'comfort': 2479, 'solitude': 12257, 'meditation': 8194, 'working': 14838, 'projects': 10309, 'nervous': 8832, 'act': 132, 'bird': 1296, 'air': 324, 'carefree': 1921, 'manner': 8026, 'revise': 11099, 'replies': 10943, 'reply': 10944, 'appropriate': 643, 'receive': 10695, 'offended': 9114, 'died': 3588, 'irrevocably': 6941, 'gone': 5655, 'alex': 357, 'matt': 8127, 'regretful': 10811, 'visit': 14381, 'educating': 4154, 'families': 4790, 'supporting': 12939, 'educationg': 4157, 'mamas': 7989, 'papas': 9463, 'key': 7262, 'hostile': 6316, 'toward': 13612, 'boring': 1512, 'sewing': 11725, 'makes': 7974, 'nothing': 8980, 'fabric': 4738, 'liked': 7661, 'original': 9257, 'fragrance': 5270, 'freshen': 5321, 'lightly': 7650, 'scent': 11484, 'underwear': 13966, 'drawer': 3943, 'gorgeously': 5672, 'glamorous': 5588, 'girly': 5575, 'apart': 587, 'push': 10465, 'succeed': 12836, 'successful': 12841, 'wounding': 14873, 'process': 10257, 'underway': 13965, 'sometimes': 12282, 'added': 161, 'antagonism': 550, 'misunderstanding': 8422, 'reluctant': 10878, 'wholeheartedly': 14680, 'traditional': 13634, 'armistice': 683, 'remembrances': 10896, 'legs': 7562, 'miles': 8323, 'come': 2471, 'unfair': 13996, 'reaction': 10641, 'ways': 14544, 'blessed': 1362, 'abused': 49, 'maligned': 7984, 'anticipating': 555, 'danger': 3190, 'typing': 13872, 'gosman': 5674, 'touristy': 13608, 'montauk': 8505, 'area': 666, 'infrequent': 6700, 'visitors': 14385, 'harbor': 5950, 'cawing': 2011, 'seagulls': 11567, 'lapping': 7439, 'water': 14532, 'wood': 14820, 'pilings': 9806, 'breeze': 1618, 'admit': 198, 'hilarious': 6165, 'cards': 1914, 'exactly': 4559, 'moment': 8473, 'hy': 6408, 'dull': 4034, 'inarticulate': 6584, 'normal': 8959, 'kick': 7276, 'gear': 5475, 'irritable': 6943, 'motivation': 8562, 'innocent': 6735, 'illustrating': 6492, 'satisfaction': 11426, 'contributing': 2782, 'looter': 7813, 'driven': 3983, 'consumerism': 2727, 'corpse': 2852, 'america': 441, 'revered': 11091, 'younger': 14994, 'resentful': 10984, 'vacation': 14221, 'obligations': 9066, 'headaches': 6016, 'emotional': 4277, 'blackmailed': 1330, 'places': 9864, 'herpes': 6128, 'checkup': 2141, 'clinic': 2335, 'wednesday': 14575, 'worked': 14835, 'try': 13788, 'disheartened': 3716, 'bitchy': 1313, 'upon': 14161, 'retrospect': 11069, 'shake': 11745, 'second': 11585, 'terrible': 13276, 'making': 7977, 'definitive': 3354, 'decisions': 3295, 'certain': 2053, 'truths': 13787, 'eggs': 4184, 'benedict': 1207, 'equally': 4441, 'delicious': 3375, 'summery': 12894, 'elements':

In [25]:
#tf-idf
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['text'])
y = df['label']
print("vocabulary:", vectorizer.vocabulary_)

vocabulary: {'didnt': 3586, 'feel': 4887, 'humiliated': 6372, 'go': 5634, 'feeling': 4891, 'hopeless': 6284, 'damned': 3176, 'hopeful': 6282, 'around': 690, 'someone': 12275, 'cares': 1927, 'awake': 916, 'im': 6495, 'grabbing': 5690, 'minute': 8373, 'post': 10050, 'greedy': 5751, 'wrong': 14901, 'ever': 4526, 'nostalgic': 8971, 'fireplace': 5016, 'know': 7352, 'still': 12622, 'property': 10329, 'grouchy': 5789, 'ive': 6986, 'little': 7728, 'burdened': 1749, 'lately': 7456, 'wasnt': 14521, 'sure': 12954, 'taking': 13111, 'milligrams': 8332, 'times': 13472, 'recommended': 10724, 'amount': 456, 'fallen': 4778, 'asleep': 755, 'lot': 7829, 'faster': 4824, 'also': 408, 'like': 7658, 'funny': 5403, 'confused': 2650, 'life': 7633, 'teenager': 13220, 'jaded': 7000, 'year': 14954, 'old': 9150, 'man': 7994, 'petronas': 9723, 'years': 14962, 'performed': 9651, 'well': 14607, 'made': 7935, 'huge': 6351, 'profit': 10287, 'romantic': 11224, 'make': 7970, 'suffering': 12861, 'seeing': 11605, 'mean': 8162, 'something': 12279, 'running': 11307, 'divine': 3807, 'experience': 4656, 'expect': 4646, 'type': 13867, 'spiritual': 12418, 'encounter': 4318, 'think': 13368, 'easiest': 4104, 'time': 13467, 'dissatisfied': 3762, 'low': 7856, 'energy': 4352, 'thirsty': 13375, 'immense': 6518, 'sympathy': 13067, 'general': 5491, 'point': 9951, 'possible': 10048, 'proto': 10358, 'writer': 14893, 'trying': 13791, 'find': 4992, 'write': 14892, 'corners': 2847, 'sign': 11929, 'agent': 286, 'let': 7595, 'alone': 399, 'publishing': 10417, 'contract': 2770, 'feels': 4894, 'precious': 10118, 'reassured': 10684, 'anxiety': 570, 'side': 11911, 'really': 10674, 'embarrassed': 4249, 'pretty': 10196, 'pathetic': 9544, 'started': 12549, 'sentimental': 11671, 'dolls': 3846, 'child': 2180, 'began': 1148, 'collection': 2439, 'vintage': 14361, 'barbie': 1035, 'sixties': 12004, 'compromised': 2583, 'skeptical': 12015, 'value': 14237, 'every': 4529, 'unit': 14042, 'work': 14833, 'put': 10472, 'irritated': 6946, 'rejected': 10827, 'without': 14782, 'anyone': 576, 'anything': 578, 'saying': 11452, 'completely': 2561, 'overwhelmed': 9365, 'two': 13859, 'strategies': 12690, 'help': 6100, 'grounded': 5791, 'pour': 10075, 'heart': 6044, 'journal': 7131, 'form': 5229, 'letter': 7601, 'god': 5638, 'end': 4325, 'list': 7709, 'five': 5035, 'things': 13366, 'grateful': 5734, 'amused': 467, 'delighted': 3378, 'able': 24, 'chai': 2064, 'lifeline': 7634, 'support': 12935, 'encouragement': 4322, 'great': 5744, 'glad': 5584, 'already': 406, 'fucked': 5369, 'though': 13387, 'dont': 3861, 'usually': 14202, 'eat': 4111, 'morning': 8536, 'love': 7845, 'wish': 14765, 'best': 1233, 'longer': 7791, 'tolerate': 13532, 'effect': 4162, 'bm': 1435, 'lives': 7737, 'fact': 4750, 'turned': 13826, 'bitter': 1320, 'angry': 508, 'person': 9686, 'always': 426, 'particularly': 9503, 'kind': 7300, 'people': 9629, 'stressed': 12706, 'inhibited': 6715, 'elses': 4231, 'kitchen': 7319, 'painting': 9423, 'picture': 9786, 'become': 1124, 'defeated': 3331, 'kinda': 7301, 'appalled': 607, 'needs': 8800, 'explain': 4666, 'wide': 14696, 'lenghth': 7573, 'body': 1452, 'measures': 8172, 'etc': 4487, 'pp': 10086, 'superior': 12916, 'dead': 3251, 'chicken': 2175, 'grieving': 5766, 'get': 5533, 'giddy': 5551, 'elegant': 4213, 'perfectly': 9647, 'fitted': 5033, 'pencil': 9617, 'skirt': 12038, 'remember': 10891, 'acutely': 154, 'distressed': 3787, 'days': 3242, 'seen': 11615, 'heard': 6040, 'read': 10646, 'past': 9533, 'couple': 2898, 'left': 7545, 'impressed': 6557, 'companies': 2528, 'climbed': 2332, 'hill': 6167, 'frustrated': 5362, 'id': 6442, 'much': 8618, 'paced': 9389, 'entirely': 4404, 'course': 2903, 'factor': 4751, 'never': 8853, 'hampered': 5900, 'dent': 3416, 'day': 3236, 'imagine': 6503, 'real': 10659, 'scenario': 11480, 'would': 14868, 'emotionally': 4278, 'connected': 2663, 'enough': 4376, 'totally': 13586, 'accepted': 67, 'safe': 11354, 'morally': 8523, 'acceptable': 64, 'close': 2350, 'prolonged': 10310, 'physical': 9764, 'contact': 2732, 'sex': 11726, 'expected': 4649, 'subsequently': 12822, 'content': 2749, 'need': 8791, 'creative': 2978, 'however': 6335, 'want': 14482, 'causing': 2004, 'less': 7588, 'splendid': 12428, 'self': 11632, 'step': 12598, 'away': 923, 'bit': 1308, 'rude': 11283, 'writing': 14897, 'elderly': 4204, 'gentleman': 5511, 'ask': 751, 'gifts': 5555, 'christmas': 2231, 'mild': 8320, 'greed': 5750, 'protected': 10348, 'small': 12120, 'season': 11577, 'words': 14831, 'plan': 9869, 'share': 11766, 'everyday': 4533, 'stories': 12662, 'traveling': 13691, 'adventures': 230, 'inspirations': 6773, 'handmade': 5916, 'creations': 2977, 'hope': 6280, 'inspired': 6775, 'trees': 13713, 'got': 5676, 'festive': 4922, 'spurring': 12482, 'book': 1491, 'worn': 14851, 'concealer': 2591, 'brave': 1592, 'pale': 9437, 'perfect': 9645, 'strongly': 12741, 'passionate': 9528, 'jerk': 7061, 'decides': 3292, 'poke': 9960, 'fun': 5390, 'us': 14185, 'discouraged': 3691, 'robbing': 11193, 'peter': 9720, 'pay': 9570, 'paul': 9560, 'cow': 2920, 'cant': 1876, 'afford': 264, 'way': 14542, 'listless': 7718, 'new': 8858, 'different': 3596, 'lost': 7828, 'special': 12369, 'mind': 8344, 'worry': 14854, 'sane': 11399, 'wanted': 14484, 'felt': 4903, 'reading': 10651, 'many': 8035, 'said': 11361, 'sam': 11383, 'guarantee': 5811, 'used': 14192, 'paragraph': 9471, 'tell': 13232, 'sad': 11344, 'first': 5022, 'home': 6237, 'mine': 8350, 'boat': 1441, 'trip': 13748, 'denmark': 3411, 'stopped': 12655, 'cold': 2423, 'hot': 6318, 'dough': 3900, 'found': 5253, 'selfish': 11633, 'spoiled': 12434, 'stymied': 12793, 'wrote': 14906, 'unsure': 14120, 'might': 8312, 'somewhere': 12285, 'story': 12667, 'unintended': 14035, 'bag': 983, 'qaf': 10485, 'look': 7798, 'cryin': 3070, 'jacynthe': 6999, 'lookin': 7800, 'good': 5658, 'feelin': 4890, 'gorgeous': 5671, 'rupaul': 11310, 'skins': 12033, 'scissor': 11513, 'sisters': 11989, 'valentine': 14228, 'sun': 12898, 'fed': 4871, 'kayle': 7241, 'daddy': 3157, 'gerling': 5524, 'unkind': 14052, 'basically': 1065, 'fake': 4775, 'realm': 10675, 'science': 11507, 'fiction': 4938, 'hate': 5988, 'living': 7739, 'dads': 3159, 'roof': 11231, 'gives': 5581, 'excuse': 4598, 'asshole': 778, 'hes': 6132, 'providing': 10372, 'live': 7730, 'unwelcome': 14135, 'ill': 6482, 'leave': 7533, 'keep': 7244, 'pleasantly': 9910, 'surprised': 12969, 'supportiveness': 12941, 'ease': 4100, 'situations': 12001, 'anymore': 575, 'vigorous': 14349, 'sexual': 11730, 'activity': 144, 'coming': 2487, 'yes': 14971, 'misspelt': 8410, 'cumming': 3095, 'parts': 9511, 'begin': 1151, 'fall': 4777, 'mom': 8471, 'graceful': 5693, 'warm': 14496, 'loving': 7855, 'smile': 12135, 'rob': 11191, 'nurture': 9033, 'heal': 6030, 'talk': 13119, 'brother': 1664, 'law': 7484, 'extremely': 4715, 'popular': 10008, 'one': 9172, 'stiff': 12621, 'ate': 805, 'could': 2875, 'gentle': 5510, 'tingle': 13480, 'throughout': 13418, 'almost': 397, 'healing': 6032, 'place': 9861, 'cellular': 2036, 'level': 7606, 'pressured': 10181, 'young': 14993, 'beautiful': 1119, 'thin': 13364, 'depending': 3430, 'trend': 13719, 'girls': 5574, 'rejuvenated': 10833, 'butt': 1786, 'implants': 6539, 'several': 11721, 'week': 14579, 'tortured': 13577, 'hallucinations': 5896, 'moving': 8601, 'figures': 4963, 'sounds': 12334, 'vibrations': 14324, 'nearly': 8781, 'finished': 5004, 'detox': 3526, 'amazing': 429, 'back': 958, 'former': 5234, 'posts': 10058, 'asked': 752, 'prayers': 10110, 'others': 9276, 'considered': 2693, 'may': 8141, 'deserve': 3467, 'answered': 547, 'pain': 9414, 'parents': 9485, 'enraged': 4379, 'becomes': 1125, 'violent': 14365, 'roller': 11217, 'coaster': 2389, 'emotions': 4281, 'supposed': 12944, 'feelings': 4893, 'unpleasant': 14077, 'suppose': 12943, 'truth': 13784, 'shared': 11767, 'havent': 6005, 'faithful': 4772, 'dwelled': 4069, 'doubt': 3893, 'uncertainty': 13922, 'faith': 4771, 'bought': 1534, 'clearly': 2313, 'makeup': 7975, 'miserable': 8386, 'proudest': 10361, 'mum': 8645, 'earth': 4096, 'figure': 4961, 'family': 4791, 'loves': 7853, 'matter': 8129, 'else': 4230, 'michelle': 8298, 'goes': 5646, 'ballistic': 1004, 'necessarily': 8784, 'bombs': 1475, 'necessary': 8785, 'see': 11601, 'print': 10227, 'journals': 7136, 'ovaries': 9316, 'aching': 116, 'talking': 13122, 'chris': 2224, 'mostly': 8551, 'took': 13557, 'pictures': 9788, 'unimportant': 14029, 'stuff': 12768, 'tired': 13494, 'ready': 10656, 'finding': 4993, 'given': 5579, 'unsuitable': 14116, 'images': 6499, 'blamed': 1342, 'result': 11047, 'sit': 11990, 'successfully': 12842, 'manage': 7995, 'stretch': 12711, 'mxm': 8691, 'canvas': 1881, 'achievement': 113, 'worthwhile': 14865, 'usage': 14187, 'money': 8490, 'use': 14191, 'future': 5413, 'briefs': 1632, 'nay': 8773, 'important': 6548, 'honored': 6270, 'influence': 6686, 'talented': 13115, 'fully': 5387, 'alive': 374, 'girl': 5570, 'woman': 14805, 'angered': 503, 'firey': 5017, 'piece': 9791, 'garbage': 5447, 'leanne': 7520, 'thought': 13388, 'miss': 8400, 'drove': 3995, 'dannika': 3197, 'school': 11501, 'rushed': 11315, 'greeted': 5755, 'corner': 2846, 'hellip': 6098, 'furious': 5405, 'shooter': 11846, 'happy': 5945, 'excited': 4589, 'since': 11962, 'learned': 7524, 'shows': 11888, 'show': 11879, 'horses': 6308, 'trusting': 13780, 'relaxed': 10850, 'quiet': 10515, 'handled': 5914, 'frequently': 5318, 'start': 12548, 'december': 3285, 'done': 3856, 'smug': 12158, 'realize': 10670, 'everything': 4537, 'ok': 9145, 'worthless': 14863, 'struggling': 12752, 'lay': 7491, 'bed': 1129, 'dark': 3202, 'terrified': 13279, 'least': 7531, 'meet': 8200, 'airport': 327, 'supportive': 12940, 'arms': 686, 'today': 13513, 'mood': 8511, 'strange': 12681, 'entire': 4402, 'guess': 5817, 'mums': 8650, 'passed': 9518, 'involved': 6913, 'car': 1900, 'accident': 75, 'bringing': 1639, 'present': 10167, 'exams': 4570, 'flying': 5152, 'colours': 2459, 'letting': 7603, 'animosity': 518, 'towards': 13613, 'wronged': 14902, 'dogs': 3840, 'cannot': 1872, 'understand': 13956, 'decided': 3290, 'throwing': 13420, 'shitty': 11831, 'shit': 11829, 'paper': 9464, 'starting': 12552, 'wryly': 14908, 'banal': 1012, 'comedy': 2476, 'errors': 4458, 'turning': 13827, 'vital': 14389, 'bodies': 1449, 'hear': 6039, 'owners': 9377, 'victimized': 14329, 'associations': 789, 'attorneys': 856, 'manager': 7999, 'say': 11451, 'goodbye': 5659, 'fam': 4785, 'theyre': 13355, 'crying': 3071, 'heartless': 6055, 'bitch': 1309, 'hey': 6140, 'spend': 12394, 'another': 543, 'country': 2895, 'wont': 14819, 'cry': 3069, 'lily': 7669, 'going': 5648, 'opportunities': 9211, 'lasted': 7452, 'short': 11855, 'months': 8509, 'alba': 345, 'fitting': 5034, 'ton': 13545, 'catching': 1984, 'word': 14830, 'helps': 6106, 'hard': 5951, 'works': 14845, 'obtain': 9083, 'high': 6153, 'technical': 13206, 'skill': 12021, 'wushu': 14913, 'ashamed': 741, 'somehow': 12272, 'motivated': 8560, 'saw': 11450, 'kids': 7287, 'performances': 9650, 'whole': 14679, 'heartedly': 6054, 'despite': 3492, 'tiredness': 13495, 'getting': 5537, 'overwhelming': 9366, 'spritz': 12477, 'toner': 13548, 'calm': 1837, 'soothe': 12307, 'effort': 4176, 'required': 10972, 'better': 1243, 'situation': 12000, 'whether': 14646, 'member': 8222, 'college': 2443, 'friend': 5330, 'neighbor': 8812, 'street': 12698, 'even': 4519, 'complete': 2559, 'stranger': 12683, 'tree': 13712, 'soon': 12298, 'goings': 5649, 'ons': 9181, 'coronation': 2850, 'seriously': 11695, 'alright': 407, 'class': 2290, 'combination': 2465, 'unsuccessful': 14115, 'stress': 12705, 'late': 7455, 'horrible': 6299, 'resulted': 11048, 'grappling': 5730, 'rarely': 10609, 'advances': 226, 'cause': 2001, 'stick': 12615, 'rule': 11297, 'posting': 10054, 'online': 9179, 'wouldnt': 14869, 'prepared': 10158, 'somebodys': 12270, 'face': 4741, 'useful': 14193, 'pains': 9419, 'becoming': 1126, 'group': 5794, 'idea': 6444, 'ugly': 13886, 'inclined': 6605, 'wear': 14556, 'ratty': 10621, 'jeans': 7048, 'sweatshirt': 13022, 'dress': 3961, 'pair': 9426, 'heels': 6080, 'house': 6327, 'boost': 1500, 'esteem': 4480, 'slightly': 12077, 'definitely': 3352, 'bother': 1523, 'buy': 1795, 'homesick': 6250, 'yet': 14974, 'dance': 3181, 'workout': 14842, 'fabulous': 4740, 'eyes': 4731, 'touch': 13592, 'assuredly': 799, 'return': 11070, 'shall': 11750, 'vain': 14226, 'friday': 5327, 'awful': 929, 'cramps': 2945, 'honoured': 6271, 'call': 1829, 'friends': 5333, 'brotherhood': 1665, 'begun': 1156, 'apprehensive': 636, 'thick': 13358, 'black': 1328, 'rain': 10567, 'clouds': 2362, 'stormed': 12664, 'sky': 12042, 'town': 13618, 'stated': 12563, 'reason': 10680, 'fearful': 4855, 'unsafe': 14099, 'shaken': 11746, 'tsa': 13793, 'quite': 10525, 'pulled': 10422, 'croissants': 3027, 'lunch': 7894, 'groups': 5795, 'awkward': 932, 'overcompensate': 9327, 'talkative': 13120, 'finally': 4985, 'companion': 2529, 'especially': 4470, 'lonely': 7786, 'disappoint': 3658, 'loved': 7848, 'blog': 1387, 'img': 6510, 'src': 12501, 'http': 6342, 'eager': 4078, 'quilting': 10521, 'horny': 6297, 'lets': 7599, 'poem': 9944, 'pressure': 10180, 'uncomfortable': 13928, 'sense': 11659, 'understanding': 13958, 'land': 7425, 'raising': 10576, 'son': 12286, 'father': 4832, 'ancestral': 483, 'shower': 11883, 'questioning': 10509, 'fantastic': 4805, 'confident': 2634, 'movement': 8594, 'effortlessly': 4177, 'energetic': 4345, 'bouncy': 1541, 'gym': 5858, 'run': 11301, 'outside': 9307, 'take': 13104, 'pram': 10101, 'long': 7788, 'walk': 14459, 'often': 9136, 'three': 13400, 'strong': 12738, 'burst': 1770, 'tears': 13198, 'devastating': 3532, 'release': 10852, 'thoughts': 13391, 'seemed': 11611, 'rich': 11123, 'space': 12345, 'dumping': 4045, 'pumpkin': 10432, 'spice': 12400, 'latte': 7463, 'last': 7451, 'thing': 13365, 'coffee': 2406, 'maybe': 8142, 'badly': 979, 'shes': 11801, 'hyperchondria': 6417, 'exaggeration': 4562, 'habit': 5863, 'openly': 9196, 'questioned': 10508, 'clench': 2316, 'assured': 798, 'called': 1831, 'figured': 4962, 'right': 11138, 'name': 8726, 'utterly': 14214, 'affirmed': 263, 'question': 10506, 'perhaps': 9657, 'office': 9125, 'nice': 8879, 'hair': 5880, 'rebellious': 10690, 'celebrates': 2025, 'eid': 4191, 'wash': 14516, 'generous': 5504, 'sleep': 12060, 'deprived': 3446, 'sleeping': 12061, 'night': 8897, 'giving': 5582, 'bloging': 1391, 'sitting': 11998, 'amp': 459, 'cat': 1979, 'lucky': 7876, 'woke': 14802, 'sick': 11906, 'dog': 3839, 'protect': 10347, 'witch': 14774, 'hunt': 6390, 'repressed': 10957, 'memory': 8230, 'therapy': 13345, 'disgusted': 3712, 'associated': 787, 'race': 10538, 'nationality': 8757, 'laughed': 7468, 'bitterly': 1321, 'wished': 14766, 'knew': 7338, 'hated': 5989, 'forever': 5216, 'mellow': 8211, 'soft': 12239, 'easy': 4109, 'beginning': 1152, 'told': 13530, 'indecisive': 6632, 'genre': 5508, 'disservice': 3764, 'resolved': 11005, 'artifically': 717, 'artistic': 723, 'manitz': 8022, 'draw': 3942, 'circle': 2258, 'dot': 3887, 'bigger': 1270, 'line': 7683, 'accent': 61, 'mark': 8056, 'spanish': 12352, 'pissed': 9843, 'brazil': 1595, 'bus': 1775, 'steep': 12590, 'mountain': 8578, 'hills': 6169, 'middle': 8304, 'big': 1268, 'storm': 12663, 'wondering': 14815, 'whimper': 14650, 'unloved': 14063, 'uncared': 13918, 'certainly': 2054, 'whats': 14632, 'personal': 9688, 'curious': 3105, 'youd': 14991, 'watch': 14526, 'sorry': 12320, 'humor': 6377, 'foot': 5190, 'door': 3872, 'world': 14847, 'walking': 14461, 'trails': 13643, 'fells': 4902, 'mountains': 8579, 'whatever': 14629, 'comes': 2477, 'directly': 3640, 'jealous': 7043, 'insecure': 6751, 'trust': 13778, 'worthy': 14866, 'sweet': 13028, 'holiday': 6221, 'influenced': 6687, 'dash': 3213, 'happiness': 5942, 'emily': 4267, 'dickinson': 3582, 'example': 4568, 'dashes': 3216, 'instead': 6784, 'colons': 2449, 'semi': 11642, 'enhance': 4363, 'enjambment': 4364, 'sonnet': 12293, 'fatter': 4837, 'remain': 10882, 'control': 2785, 'peanut': 9588, 'butter': 1787, 'bread': 1599, 'impossible': 6551, 'looking': 7801, 'third': 13374, 'hell': 6096, 'needy': 8801, 'neglected': 8808, 'claim': 2274, 'redeem': 10748, 'beating': 1115, 'head': 6014, 'wall': 14463, 'either': 4196, 'classes': 2291, 'intimidated': 6873, 'concept': 2596, 'lit': 7720, 'groggy': 5782, 'routine': 11263, 'view': 14341, 'isnt': 6959, 'thats': 13322, 'fine': 4995, 'hold': 6214, 'shocked': 11836, 'awe': 924, 'wonder': 14810, 'rumour': 11300, 'st': 12506, 'exam': 4563, 'results': 11050, 'fear': 4853, 'failures': 4764, 'valued': 14238, 'appreciated': 632, 'arent': 669, 'anywhere': 582, 'nature': 8763, 'relationship': 10843, 'changes': 2089, 'distracted': 3781, 'regularly': 10815, 'relaxing': 10851, 'music': 8674, 'invigorated': 6905, 'afterward': 280, 'tend': 13253, 'practice': 10091, 'shut': 11898, 'youtube': 15000, 'influences': 6688, 'trends': 13721, 'specifically': 12377, 'tango': 13135, 'shy': 11901, 'maks': 7978, 'opposite': 9215, 'far': 4808, 'pics': 9785, 'lol': 7778, 'weird': 14598, 'slept': 12068, 'okay': 9146, 'thinking': 13370, 'earlier': 4086, 'heres': 6120, 'cooped': 2818, 'restless': 11036, 'weight': 14591, 'fit': 5029, 'tiny': 13487, 'unable': 13900, 'presence': 10166, 'fan': 4794, 'current': 3113, 'president': 10176, 'conservative': 2686, 'enclose': 4314, 'verses': 14308, 'weigh': 14587, 'odd': 9104, 'complacent': 2552, 'vulnerable': 14432, 'parenting': 9484, 'punished': 10440, 'stupid': 12783, 'chastised': 2123, 'behaving': 1161, 'stay': 12578, 'simply': 11956, 'contented': 2750, 'cut': 3133, 'everyone': 4535, 'comfort': 2479, 'solitude': 12257, 'meditation': 8194, 'working': 14838, 'projects': 10309, 'nervous': 8832, 'act': 132, 'bird': 1296, 'air': 324, 'carefree': 1921, 'manner': 8026, 'revise': 11099, 'replies': 10943, 'reply': 10944, 'appropriate': 643, 'receive': 10695, 'offended': 9114, 'died': 3588, 'irrevocably': 6941, 'gone': 5655, 'alex': 357, 'matt': 8127, 'regretful': 10811, 'visit': 14381, 'educating': 4154, 'families': 4790, 'supporting': 12939, 'educationg': 4157, 'mamas': 7989, 'papas': 9463, 'key': 7262, 'hostile': 6316, 'toward': 13612, 'boring': 1512, 'sewing': 11725, 'makes': 7974, 'nothing': 8980, 'fabric': 4738, 'liked': 7661, 'original': 9257, 'fragrance': 5270, 'freshen': 5321, 'lightly': 7650, 'scent': 11484, 'underwear': 13966, 'drawer': 3943, 'gorgeously': 5672, 'glamorous': 5588, 'girly': 5575, 'apart': 587, 'push': 10465, 'succeed': 12836, 'successful': 12841, 'wounding': 14873, 'process': 10257, 'underway': 13965, 'sometimes': 12282, 'added': 161, 'antagonism': 550, 'misunderstanding': 8422, 'reluctant': 10878, 'wholeheartedly': 14680, 'traditional': 13634, 'armistice': 683, 'remembrances': 10896, 'legs': 7562, 'miles': 8323, 'come': 2471, 'unfair': 13996, 'reaction': 10641, 'ways': 14544, 'blessed': 1362, 'abused': 49, 'maligned': 7984, 'anticipating': 555, 'danger': 3190, 'typing': 13872, 'gosman': 5674, 'touristy': 13608, 'montauk': 8505, 'area': 666, 'infrequent': 6700, 'visitors': 14385, 'harbor': 5950, 'cawing': 2011, 'seagulls': 11567, 'lapping': 7439, 'water': 14532, 'wood': 14820, 'pilings': 9806, 'breeze': 1618, 'admit': 198, 'hilarious': 6165, 'cards': 1914, 'exactly': 4559, 'moment': 8473, 'hy': 6408, 'dull': 4034, 'inarticulate': 6584, 'normal': 8959, 'kick': 7276, 'gear': 5475, 'irritable': 6943, 'motivation': 8562, 'innocent': 6735, 'illustrating': 6492, 'satisfaction': 11426, 'contributing': 2782, 'looter': 7813, 'driven': 3983, 'consumerism': 2727, 'corpse': 2852, 'america': 441, 'revered': 11091, 'younger': 14994, 'resentful': 10984, 'vacation': 14221, 'obligations': 9066, 'headaches': 6016, 'emotional': 4277, 'blackmailed': 1330, 'places': 9864, 'herpes': 6128, 'checkup': 2141, 'clinic': 2335, 'wednesday': 14575, 'worked': 14835, 'try': 13788, 'disheartened': 3716, 'bitchy': 1313, 'upon': 14161, 'retrospect': 11069, 'shake': 11745, 'second': 11585, 'terrible': 13276, 'making': 7977, 'definitive': 3354, 'decisions': 3295, 'certain': 2053, 'truths': 13787, 'eggs': 4184, 'benedict': 1207, 'equally': 4441, 'delicious': 3375, 'summery': 12894, 'elements':